### ISSUE TITLE
HELP!!!!

### ISSUE THREAD

**Issue by whiitees** [Wokzy/blum-bot#13]
When I start program in terminal, and then I click play on blum program does't collect any green coins :(
HELP!!!

**Comment by whiitees** [comment]
code doen't detect runing game

**Comment by Wokzy** [comment]
Hello. It usually happens, the issue is related to Windows kernel, which sometimes "lies" to my script, that the window was detected properly. Couple of thing that may help: disable notifications in telegram and rerun the script. After you ran the script, game window **must become the top window automatically**, if that happens, you may be sure that the script will collect "green coins", otherwise rerun the script until that happens.

**Comment by whiitees** [comment]
Ye when I run the script it make the game window get on top but it isn't collect any green coins
