### ISSUE TITLE
New Blum Update

### ISSUE THREAD

**Issue by RensNaz** [Wokzy/blum-bot#6]
Blum will soon update the game in this way.Can you please update the script so that it also clicks on the dogs and notcoins items.

![blu,](https://github.com/user-attachments/assets/b4456e64-6bef-43f8-8ef0-e9b096056680)

**Comment by Wokzy** [comment]
Thanks a lot for such inside info)
To implement new update, it's nessesarry to have a pure screenshot, not a compressed image, so that all pixels of game screen are not corrupted. If you could't attach it, it's not a problem. Im actively following Blum news, so when update will be released, I'll try to update my script asap.

**Comment by Wokzy** [comment]
> Hi i never download anything from github could you explain how i can use the script on my labtop

Click on big button called "<>code" above repo and download code in a comfortable way, then just follow instructions described in README.md

**Comment by Wokzy** [comment]
1. No, this code was written using windows api library, so it only works on windows
2. Fixes were described in this issue: https://github.com/Wokzy/blum-bot/issues/8
